import cron from 'node-cron';
import RecurringExpense from './models/RecurringExpense.js';
import Expense from './models/Expense.js';

const getNextRunDate = (date, frequency) => {
  const current = new Date(date);
  switch (frequency) {
    case 'daily':
      current.setDate(current.getDate() + 1);
      break;
    case 'weekly':
      current.setDate(current.getDate() + 7);
      break;
    case 'monthly':
      current.setMonth(current.getMonth() + 1);
      break;
    case 'yearly':
      current.setFullYear(current.getFullYear() + 1);
      break;
  }
  return current;
};

export const startCronJobs = () => {
  // Run daily at midnight '0 0 * * *'
  cron.schedule('0 0 * * *', async () => {
    console.log('Running daily Recurring Expense sweep...', new Date());
    
    try {
      const now = new Date();
      const dueExpenses = await RecurringExpense.find({
        isActive: true,
        nextRunDate: { $lte: now }
      });

      for (const reqExp of dueExpenses) {
        // 1. Create standard Expense
        await Expense.create({
          userId: reqExp.userId,
          type: 'expense',
          amount: reqExp.amount,
          category: reqExp.category,
          paymentMode: reqExp.paymentMode,
          description: reqExp.description,
          notes: 'Auto-generated by recurring schedule',
          date: reqExp.nextRunDate,
          isSplit: false
        });

        // 2. Advance the recurrence
        reqExp.lastRunDate = reqExp.nextRunDate;
        reqExp.nextRunDate = getNextRunDate(reqExp.nextRunDate, reqExp.frequency);
        await reqExp.save();
        
        console.log(`Processed recurring expense for user ${reqExp.userId} - ${reqExp.description}`);
      }
    } catch (error) {
      console.error('Cron job error:', error.message);
    }
  });
};
